-- Reproducible snapshot of reviewed, non-personal reference and cited evidence data.
-- Captured read-only from project irprsggvvfxakctlotga on 2026-07-24.
-- Runtime strategy history and collection-job state are intentionally excluded.

WITH payload AS (
  SELECT *
  FROM jsonb_to_recordset(
$tippos_mi_languages$
[
  {
    "code": "ar",
    "notes": "Requires RTL product validation",
    "native_name": "العربية",
    "english_name": "Arabic",
    "product_status": "researching",
    "text_direction": "rtl",
    "estimated_localization_cost": null
  },
  {
    "code": "bn",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "বাংলা",
    "english_name": "Bengali",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "de",
    "notes": "Candidate market",
    "native_name": "Deutsch",
    "english_name": "German",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "en",
    "notes": "Already present in the product",
    "native_name": "English",
    "english_name": "English",
    "product_status": "supported",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "es",
    "notes": "Already present in the product",
    "native_name": "Español",
    "english_name": "Spanish",
    "product_status": "supported",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "fa",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "فارسی",
    "english_name": "Persian",
    "product_status": "researching",
    "text_direction": "rtl",
    "estimated_localization_cost": null
  },
  {
    "code": "fr",
    "notes": "Candidate market",
    "native_name": "Français",
    "english_name": "French",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "gu",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "ગુજરાતી",
    "english_name": "Gujarati",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "he",
    "notes": "Requires RTL product validation",
    "native_name": "עברית",
    "english_name": "Hebrew",
    "product_status": "researching",
    "text_direction": "rtl",
    "estimated_localization_cost": null
  },
  {
    "code": "hi",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "हिन्दी",
    "english_name": "Hindi",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "ht",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "Kreyòl Ayisyen",
    "english_name": "Haitian Creole",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "it",
    "notes": "Candidate market",
    "native_name": "Italiano",
    "english_name": "Italian",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "ja",
    "notes": "Requires product and payment-market validation",
    "native_name": "日本語",
    "english_name": "Japanese",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "ko",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "한국어",
    "english_name": "Korean",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "nl",
    "notes": "Candidate market",
    "native_name": "Nederlands",
    "english_name": "Dutch",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "pl",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "Polski",
    "english_name": "Polish",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "pt",
    "notes": "Candidate market",
    "native_name": "Português",
    "english_name": "Portuguese",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "ru",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "Русский",
    "english_name": "Russian",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "tl",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "Tagalog",
    "english_name": "Tagalog",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "und",
    "notes": "Temporary classification for observations that require language enrichment",
    "native_name": "Undetermined",
    "english_name": "Undetermined",
    "product_status": "not_evaluated",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "ur",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "اردو",
    "english_name": "Urdu",
    "product_status": "researching",
    "text_direction": "rtl",
    "estimated_localization_cost": null
  },
  {
    "code": "vi",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "Tiếng Việt",
    "english_name": "Vietnamese",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  },
  {
    "code": "zh",
    "notes": "US market-language research candidate. Added from US Census ACS language-use coverage; not an automatic localization or launch decision.",
    "native_name": "中文",
    "english_name": "Chinese",
    "product_status": "researching",
    "text_direction": "ltr",
    "estimated_localization_cost": null
  }
]
$tippos_mi_languages$::jsonb
  ) AS x(
    code text,
    english_name text,
    native_name text,
    text_direction text,
    product_status text,
    estimated_localization_cost numeric,
    notes text
  )
)
INSERT INTO market_intelligence.languages (
  code,
  english_name,
  native_name,
  text_direction,
  product_status,
  estimated_localization_cost,
  notes
)
SELECT
  code,
  english_name,
  native_name,
  text_direction,
  product_status::market_intelligence.language_product_status,
  estimated_localization_cost,
  notes
FROM payload
ON CONFLICT (code) DO NOTHING;

WITH payload AS (
  SELECT *
  FROM jsonb_to_recordset(
$tippos_mi_evidence$
[
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Banco Central do Brasil",
    "confidence": 0.95,
    "metric_key": "mobile_noncash_operations",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bcb.gov.br/en/pressdetail/2614/nota/https%3A/www3.bcb.gov.br/sgspub",
    "data_nature": "third_party",
    "metric_unit": "billion_operations",
    "country_code": "BR",
    "evidence_key": "br-mobile-noncash-operations-2024",
    "metric_value": 58.9,
    "period_start": "2024-01-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Pix and cards were the most used payment instruments in Brazil in 2024",
    "claim_summary": "Mobile devices were used for 58.9 billion non-cash payment operations in Brazil during 2024.",
    "language_code": "pt",
    "methodology_notes": null,
    "strategic_relevance": "Mobile is already the dominant access channel, aligning strongly with a mobile-first tipping experience."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Banco Central do Brasil",
    "confidence": 0.95,
    "metric_key": "pix_transaction_volume_growth",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bcb.gov.br/en/pressdetail/2614/nota/https%3A/www3.bcb.gov.br/sgspub",
    "data_nature": "third_party",
    "metric_unit": "percent_year_over_year",
    "country_code": "BR",
    "evidence_key": "br-pix-growth-2024",
    "metric_value": 52,
    "period_start": "2024-01-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Pix and cards were the most used payment instruments in Brazil in 2024",
    "claim_summary": "Pix transaction volume in Brazil grew by approximately 52% during 2024.",
    "language_code": "pt",
    "methodology_notes": null,
    "strategic_relevance": "Rapid growth confirms digital-payment momentum and raises the importance of Pix-compatible product positioning."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Banco Central do Brasil",
    "confidence": 0.95,
    "metric_key": "pix_noncash_transaction_share",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bcb.gov.br/en/pressdetail/2614/nota/https%3A/www3.bcb.gov.br/sgspub",
    "data_nature": "third_party",
    "metric_unit": "percent_of_noncash_transactions_q4",
    "country_code": "BR",
    "evidence_key": "br-pix-noncash-share-2024",
    "metric_value": 47,
    "period_start": "2024-10-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Pix and cards were the most used payment instruments in Brazil in 2024",
    "claim_summary": "By the fourth quarter of 2024, Pix represented nearly 47% of non-cash payment transactions in Brazil.",
    "language_code": "pt",
    "methodology_notes": null,
    "strategic_relevance": "Brazil has exceptional instant-payment readiness, but Pix is also a powerful substitute that tippos must integrate with or differentiate from."
  },
  {
    "category": "tipping_regulation",
    "metadata": {},
    "publisher": "Presidência da República",
    "confidence": 0.98,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/l13419.htm",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "BR",
    "evidence_key": "br-tipping-law-2017",
    "metric_value": null,
    "period_start": null,
    "published_on": "2017-03-13",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Lei 13.419 de 13 de março de 2017",
    "claim_summary": "Brazilian federal law regulates the distribution and employment treatment of tips and added charges in bars, restaurants, hotels and similar establishments.",
    "language_code": "pt",
    "methodology_notes": null,
    "strategic_relevance": "A Brazilian launch would need payroll, allocation and reporting workflows that respect the local statutory treatment of tips."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Banco de España",
    "confidence": 0.95,
    "metric_key": "bizum_p2p_preference",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bde.es/wbe/en/inicio/noticias/que-importancia-tiene-el-efectivo-en-nuestros-pagos-del-dia-a-dia-0a8d5be517e3391.html",
    "data_nature": "third_party",
    "metric_unit": "percent_of_population",
    "country_code": "ES",
    "evidence_key": "es-bizum-p2p-preference-2024",
    "metric_value": 33,
    "period_start": "2024-01-01",
    "published_on": "2024-11-22",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "How important is cash in our day-to-day payments?",
    "claim_summary": "In Spain, 33% of the population preferred Bizum for person-to-person payments in 2024.",
    "language_code": "es",
    "methodology_notes": null,
    "strategic_relevance": "An established instant-transfer habit could help digital tipping adoption but also represents a strong substitute behavior."
  },
  {
    "category": "cash_reliance",
    "metadata": {},
    "publisher": "Banco de España",
    "confidence": 0.95,
    "metric_key": "daily_cash_use_population",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bde.es/wbe/en/inicio/noticias/que-importancia-tiene-el-efectivo-en-nuestros-pagos-del-dia-a-dia-0a8d5be517e3391.html",
    "data_nature": "third_party",
    "metric_unit": "percent_of_population",
    "country_code": "ES",
    "evidence_key": "es-daily-cash-use-2024",
    "metric_value": 57,
    "period_start": "2024-01-01",
    "published_on": "2024-11-22",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "How important is cash in our day-to-day payments?",
    "claim_summary": "In 2024, 57% of Spain's population used cash daily, down from 65% in 2023.",
    "language_code": "es",
    "methodology_notes": null,
    "strategic_relevance": "Spain is digitizing but remains cash-reliant, suggesting a transition market rather than a fully cashless one."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Banco de España",
    "confidence": 0.95,
    "metric_key": "non_cash_payment_operations_growth",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bde.es/wbe/es/noticias-eventos/actualidad-banco-espana/las-operaciones-de-pago-con-instrumentos-distintos-del-efectivo-aumentaron-un-105-en-el-segundo-semestre-de-2024-respecto-al-mismo-periodo-de-2023.html",
    "data_nature": "third_party",
    "metric_unit": "percent_year_over_year",
    "country_code": "ES",
    "evidence_key": "es-non-cash-operations-growth-h2-2024",
    "metric_value": 10.5,
    "period_start": "2024-07-01",
    "published_on": "2025-06-19",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Non-cash payment operations increased in the second half of 2024",
    "claim_summary": "Payment operations using non-cash instruments in Spain increased by 10.5% in the second half of 2024 compared with the same period of 2023.",
    "language_code": "es",
    "methodology_notes": null,
    "strategic_relevance": "Growing non-cash usage improves the feasibility of digital tipping, but does not by itself establish customer demand for tippos."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Banco de España",
    "confidence": 0.95,
    "metric_key": "regular_card_use_in_shops",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bde.es/wbe/en/inicio/noticias/que-importancia-tiene-el-efectivo-en-nuestros-pagos-del-dia-a-dia-0a8d5be517e3391.html",
    "data_nature": "third_party",
    "metric_unit": "percent_of_population",
    "country_code": "ES",
    "evidence_key": "es-regular-card-shop-use-2024",
    "metric_value": 30,
    "period_start": "2024-01-01",
    "published_on": "2024-11-22",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "How important is cash in our day-to-day payments?",
    "claim_summary": "Thirty percent of Spain's population regularly paid by card in shops in 2024.",
    "language_code": "es",
    "methodology_notes": null,
    "strategic_relevance": "Card familiarity exists but is not universal, so tippos would need both digital convenience and clear user education."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "UK Finance",
    "confidence": 0.9,
    "metric_key": "contactless_payment_share",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.ukfinance.org.uk/system/files/2025-10/UK%20Payment%20Markets%202025%20Summary.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_all_payments",
    "country_code": "GB",
    "evidence_key": "gb-contactless-share-2024",
    "metric_value": 39,
    "period_start": "2024-01-01",
    "published_on": "2025-10-01",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "UK Payment Markets 2025 Summary",
    "claim_summary": "Contactless methods accounted for 39% of all payments in the United Kingdom during 2024.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "High contactless usage indicates strong readiness for low-friction digital tipping at the point of service."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "UK Finance",
    "confidence": 0.9,
    "metric_key": "regular_mobile_contactless_adoption",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.ukfinance.org.uk/system/files/2025-10/UK%20Payment%20Markets%202025%20Summary.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_adults",
    "country_code": "GB",
    "evidence_key": "gb-mobile-contactless-adults-2024",
    "metric_value": 50,
    "period_start": "2024-01-01",
    "published_on": "2025-10-01",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "UK Payment Markets 2025 Summary",
    "claim_summary": "Half of United Kingdom adults used mobile contactless payments at least monthly in 2024.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "A large addressable population already understands mobile-wallet payment behavior."
  },
  {
    "category": "tipping_regulation",
    "metadata": {},
    "publisher": "UK Department for Business and Trade",
    "confidence": 0.98,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.gov.uk/government/publications/distributing-tips-fairly-statutory-code-of-practice",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "GB",
    "evidence_key": "gb-tips-allocation-law-2024",
    "metric_value": null,
    "period_start": null,
    "published_on": "2024-07-29",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Distributing tips fairly: statutory code of practice",
    "claim_summary": "From 1 October 2024, United Kingdom rules require qualifying tips to be passed to workers without deductions and allocated fairly and transparently.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "A digital tipping product must support transparent allocation records and worker-facing trust in the United Kingdom."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Bank of Israel",
    "confidence": 0.95,
    "metric_key": "card_payment_value_growth_decade",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.boi.org.il/en/communication-and-publications/press-releases/the-bank-of-israel-publishes-a-survey-of-the-main-developments-in-the-payment-and-settlement-systems-in-recent-years/",
    "data_nature": "third_party",
    "metric_unit": "percent_growth",
    "country_code": "IL",
    "evidence_key": "il-card-payment-value-growth-decade-2023",
    "metric_value": 99,
    "period_start": null,
    "published_on": "2024-08-12",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Survey of main developments in payment and settlement systems",
    "claim_summary": "The value of card payments in Israel grew by 99% over the preceding decade and reached NIS 451 billion in 2023.",
    "language_code": "he",
    "methodology_notes": null,
    "strategic_relevance": "Long-term card growth indicates broad digital-payment readiness, although it does not directly measure tipping demand."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Bank of Israel",
    "confidence": 0.9,
    "metric_key": "contactless_transaction_share",
    "period_end": "2023-04-30",
    "source_key": "codex_public_research",
    "source_url": "https://www.boi.org.il/en/communication-and-publications/press-releases/a11-07-23/",
    "data_nature": "third_party",
    "metric_unit": "approx_percent_of_card_transactions",
    "country_code": "IL",
    "evidence_key": "il-contactless-transaction-share-2023",
    "metric_value": 50,
    "period_start": "2023-04-01",
    "published_on": "2023-07-11",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Completion of shifting the payments market to the EMV standard",
    "claim_summary": "Bank of Israel reporting indicated that contactless payments represented about half of card transactions by April 2023.",
    "language_code": "he",
    "methodology_notes": null,
    "strategic_relevance": "Contactless behavior is already mainstream, supporting QR- or mobile-led tipping interactions."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Bank of Israel",
    "confidence": 0.95,
    "metric_key": "payment_app_funds_p2b_share",
    "period_end": "2023-06-30",
    "source_key": "codex_public_research",
    "source_url": "https://www.boi.org.il/en/communication-and-publications/press-releases/bank-of-israel-publishes-a-survey-of-means-of-payment-preferences-in-israel/",
    "data_nature": "third_party",
    "metric_unit": "percent_of_payment_app_funds",
    "country_code": "IL",
    "evidence_key": "il-payment-app-p2b-share-2023",
    "metric_value": 42,
    "period_start": "2023-06-01",
    "published_on": "2024-01-10",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Survey of means of payment preferences in Israel",
    "claim_summary": "A Bank of Israel survey found that 42% of funds transferred through payment applications were used to pay businesses for services and products.",
    "language_code": "he",
    "methodology_notes": null,
    "strategic_relevance": "Israel already has meaningful person-to-business payment-app behavior, lowering adoption friction for digital tipping."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Bank of Israel",
    "confidence": 0.9,
    "metric_key": "smartphone_wallet_transaction_share",
    "period_end": "2023-04-30",
    "source_key": "codex_public_research",
    "source_url": "https://www.boi.org.il/en/communication-and-publications/press-releases/a11-07-23/",
    "data_nature": "third_party",
    "metric_unit": "approx_percent_of_card_transactions",
    "country_code": "IL",
    "evidence_key": "il-smartphone-wallet-share-2023",
    "metric_value": 17,
    "period_start": "2023-04-01",
    "published_on": "2023-07-11",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Completion of shifting the payments market to the EMV standard",
    "claim_summary": "Bank of Israel reporting indicated that smartphone-wallet transactions represented around 17% of card transactions by April 2023.",
    "language_code": "he",
    "methodology_notes": null,
    "strategic_relevance": "A substantial wallet-using segment is already comfortable completing payments through a phone."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "sample_size": 2277,
      "survey_provider": "YouGov"
    },
    "publisher": "Bankrate",
    "confidence": 0.9,
    "metric_key": "adults_annoyed_by_preentered_tip_screens",
    "period_end": "2025-04-25",
    "source_key": "codex_public_research",
    "source_url": "https://www.bankrate.com/press-releases/63-of-americans-have-a-negative-view-about-tipping-with-41-saying-tipping-culture-has-gotten-out-of-control/",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-bankrate-annoyed-tip-screens-2025",
    "metric_value": 38,
    "period_start": "2025-04-23",
    "published_on": "2025-06-04",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "63% of Americans Have a Negative View About Tipping",
    "claim_summary": "Bankrate reported that 38% of US adults were annoyed by pre-entered tip screens in 2025.",
    "language_code": "en",
    "methodology_notes": "Online YouGov panel survey of 2,277 US adults using demographic quotas and weights; non-probability sample.",
    "strategic_relevance": "Supports a calm interface with an editable amount and no manipulative preselected percentage."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "sample_size": 2277,
      "survey_provider": "YouGov"
    },
    "publisher": "Bankrate",
    "confidence": 0.9,
    "metric_key": "adults_with_negative_tipping_view",
    "period_end": "2025-04-25",
    "source_key": "codex_public_research",
    "source_url": "https://www.bankrate.com/press-releases/63-of-americans-have-a-negative-view-about-tipping-with-41-saying-tipping-culture-has-gotten-out-of-control/",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-bankrate-negative-tipping-views-2025",
    "metric_value": 63,
    "period_start": "2025-04-23",
    "published_on": "2025-06-04",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "63% of Americans Have a Negative View About Tipping",
    "claim_summary": "Bankrate reported that 63% of US adults held at least one negative view about tipping in its 2025 survey.",
    "language_code": "en",
    "methodology_notes": "Online YouGov panel survey of 2,277 US adults using demographic quotas and weights; non-probability sample.",
    "strategic_relevance": "Reinforces the need for neutral, non-coercive guidance and a product experience that avoids tip-pressure patterns."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "sample_size": 2277,
      "survey_provider": "YouGov"
    },
    "publisher": "Bankrate",
    "confidence": 0.9,
    "metric_key": "adults_saying_tipping_out_of_control",
    "period_end": "2025-04-25",
    "source_key": "codex_public_research",
    "source_url": "https://www.bankrate.com/press-releases/63-of-americans-have-a-negative-view-about-tipping-with-41-saying-tipping-culture-has-gotten-out-of-control/",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-bankrate-tipping-out-of-control-2025",
    "metric_value": 41,
    "period_start": "2025-04-23",
    "published_on": "2025-06-04",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "63% of Americans Have a Negative View About Tipping",
    "claim_summary": "Bankrate reported that 41% of US adults said tipping culture had gotten out of control in 2025.",
    "language_code": "en",
    "methodology_notes": "Online YouGov panel survey of 2,277 US adults using demographic quotas and weights; non-probability sample.",
    "strategic_relevance": "Suggests Tippos should frame guidance as clarity and choice rather than encouraging tip inflation."
  },
  {
    "category": "cash_reliance",
    "metadata": {},
    "publisher": "Federal Reserve Financial Services",
    "confidence": 0.95,
    "metric_key": "cash_payment_share",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.frbservices.org/news/press-releases/051325-findings-from-2025-diary-of-consumer-payment-choice",
    "data_nature": "third_party",
    "metric_unit": "percent_of_consumer_payments_by_number",
    "country_code": "US",
    "evidence_key": "us-cash-payment-share-2024",
    "metric_value": 14,
    "period_start": "2024-01-01",
    "published_on": "2025-05-13",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "2025 Diary of Consumer Payment Choice",
    "claim_summary": "Cash accounted for 14% of United States consumer payments by number in 2024; credit cards accounted for 35% and debit cards for 30%.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Cash is a minority payment method, supporting a cashless-tip use case, while the remaining cash share shows that behavior is not fully digital."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Pew Research Center",
    "confidence": 0.95,
    "metric_key": "consumers_who_oppose_suggested_tip_amounts",
    "period_end": "2023-08-27",
    "source_key": "codex_public_research",
    "source_url": "https://www.pewresearch.org/wp-content/uploads/2023/11/SR_23.11.09_tipping-culture_report.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_us_adults",
    "country_code": "US",
    "evidence_key": "us-consumers-oppose-suggested-tips-2023",
    "metric_value": 40,
    "period_start": "2023-08-07",
    "published_on": "2023-11-09",
    "retrieved_at": "2026-07-23T00:55:11.117869+00:00",
    "source_title": "Tipping Culture in America: Public Sees a Changed Landscape",
    "claim_summary": "Forty percent of United States adults opposed businesses suggesting tip amounts, while 24% favored the practice.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "For tippos, default amounts should be optional and explained; a neutral custom amount and no-tip path are important to avoid a coercive experience."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Pew Research Center",
    "confidence": 0.95,
    "metric_key": "consumers_who_prefer_worker_keeps_direct_tips",
    "period_end": "2023-08-27",
    "source_key": "codex_public_research",
    "source_url": "https://www.pewresearch.org/wp-content/uploads/2023/11/SR_23.11.09_tipping-culture_report.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_us_adults",
    "country_code": "US",
    "evidence_key": "us-consumers-prefer-direct-tip-retention-2023",
    "metric_value": 72,
    "period_start": "2023-08-07",
    "published_on": "2023-11-09",
    "retrieved_at": "2026-07-23T00:55:11.117869+00:00",
    "source_title": "Tipping Culture in America: Public Sees a Changed Landscape",
    "claim_summary": "When asked about restaurant servers, 72% of United States adults said the fairest arrangement was for each server to keep all tips they received.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Although measured for restaurant servers, this is evidence that tippos should clearly show where a voluntary tip goes and avoid ambiguous pooling claims."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Pew Research Center",
    "confidence": 0.95,
    "metric_key": "consumers_who_find_it_easy_to_know_whether_to_tip",
    "period_end": "2023-08-27",
    "source_key": "codex_public_research",
    "source_url": "https://www.pewresearch.org/wp-content/uploads/2023/11/SR_23.11.09_tipping-culture_report.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_us_adults",
    "country_code": "US",
    "evidence_key": "us-consumers-tipping-uncertainty-2023",
    "metric_value": 34,
    "period_start": "2023-08-07",
    "published_on": "2023-11-09",
    "retrieved_at": "2026-07-23T00:55:11.117869+00:00",
    "source_title": "Tipping Culture in America: Public Sees a Changed Landscape",
    "claim_summary": "Only 34% of United States adults said it was extremely or very easy to know whether to tip for different services; 33% said the same about knowing how much to tip.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "tippos should reduce uncertainty with a clear, optional, context-specific suggestion rather than assume customers know whether or how much to give."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "applies_to": "product_privacy_design",
      "anonymity_boundary": "transaction_data_privacy"
    },
    "publisher": "Consumer Financial Protection Bureau",
    "confidence": 0.9,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.consumerfinance.gov/archive/newsroom/cfpb-finalizes-rule-on-federal-oversight-of-popular-digital-payment-apps-to-protect-personal-data-reduce-fraud-and-stop-illegal-debanking/",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-digital-payment-transaction-privacy-context-2024",
    "metric_value": null,
    "period_start": null,
    "published_on": "2024-11-21",
    "retrieved_at": "2026-07-23T01:06:06.443693+00:00",
    "source_title": "CFPB Finalizes Rule on Federal Oversight of Popular Digital Payment Apps",
    "claim_summary": "The CFPB has warned that large digital-payment providers can collect substantial transaction data, reinforcing that payment privacy must be designed deliberately rather than assumed.",
    "language_code": "en",
    "methodology_notes": "Regulatory and privacy context, not a measurement of tipper preferences.",
    "strategic_relevance": "tippos should minimize personal data shown to a worker or venue, disclose what is visible to each party, and avoid overclaiming privacy."
  },
  {
    "category": "service_market",
    "metadata": {},
    "publisher": "U.S. Bureau of Labor Statistics",
    "confidence": 0.95,
    "metric_key": "food_beverage_serving_related_jobs",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bls.gov/ooh/food-preparation-and-serving/food-and-beverage-serving-and-related-workers.htm",
    "data_nature": "third_party",
    "metric_unit": "jobs",
    "country_code": "US",
    "evidence_key": "us-food-beverage-service-workers-2024",
    "metric_value": 5000000,
    "period_start": "2024-01-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:50:20.811281+00:00",
    "source_title": "Food and Beverage Serving and Related Workers: Occupational Outlook Handbook",
    "claim_summary": "Food and beverage serving and related workers held about 5.0 million jobs in the United States in 2024; 82% of those workers were employed in food services and drinking places.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "This identifies a large, tip-relevant service workforce, but it does not measure willingness to adopt tippos."
  },
  {
    "category": "service_market",
    "metadata": {},
    "publisher": "U.S. Bureau of Labor Statistics",
    "confidence": 0.98,
    "metric_key": "hotel_housekeeping_workers",
    "period_end": "2024-05-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bls.gov/oes/2024/may/ind_emp_chart/ind_emp_chart_data.htm",
    "data_nature": "third_party",
    "metric_unit": "jobs",
    "country_code": "US",
    "evidence_key": "us-hotel-housekeeping-employment-2024",
    "metric_value": 417160,
    "period_start": "2024-05-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:51:26.600753+00:00",
    "source_title": "Data tables for OEWS industry charts",
    "claim_summary": "The United States traveler-accommodation industry employed 417,160 maids and housekeeping cleaners in May 2024.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Hotel housekeeping is a large, clearly defined initial service segment for tippos. This measures employment, not tipping frequency or product demand."
  },
  {
    "category": "tipping_regulation",
    "metadata": {},
    "publisher": "U.S. Department of Labor",
    "confidence": 0.95,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.dol.gov/agencies/whd/fact-sheets/45-flsa-hotels",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-hotel-tip-compliance-context",
    "metric_value": null,
    "period_start": null,
    "published_on": "2020-01-01",
    "retrieved_at": "2026-07-23T00:51:26.600753+00:00",
    "source_title": "Fact Sheet #45: Hotel and Motel Establishments Under the FLSA",
    "claim_summary": "Federal hotel guidance says an employee is tipped only when the occupation customarily and regularly receives more than 30 dollars per month in tips; employers using a tip credit must follow notice, wage, recordkeeping, and distribution requirements. State laws may be more protective.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "A tippos hotel-housekeeping rollout needs worker-level tip ownership, transparent distribution, and state-by-state legal review. This does not classify every housekeeper as a tipped employee."
  },
  {
    "category": "service_market",
    "metadata": {},
    "publisher": "U.S. Bureau of Labor Statistics",
    "confidence": 0.95,
    "metric_key": "maids_housekeeping_cleaners_annual_mean_wage",
    "period_end": "2024-05-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.bls.gov/oes/2024/may/featured_data.htm",
    "data_nature": "third_party",
    "metric_unit": "usd_annual_mean_wage",
    "country_code": "US",
    "evidence_key": "us-housekeeping-mean-wage-2024",
    "metric_value": 36180,
    "period_start": "2024-05-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:51:26.600753+00:00",
    "source_title": "Data tables for the overview of May 2024 occupational employment and wages",
    "claim_summary": "The national annual mean wage for maids and housekeeping cleaners was 36,180 US dollars in May 2024.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "This provides worker-economics context for the segment, but does not establish take-home pay, tip income, or willingness to use tippos."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "Asian/Pacific Island language coverage",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-bengali-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "bn",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "direct Census category",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.9,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-chinese-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "zh",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "other Indo-European aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-gujarati-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "gu",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "French/Haitian/Cajun aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-haitian-creole-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "ht",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "other Indo-European aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-hindi-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "hi",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "direct Census category",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.9,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-korean-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "ko",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "other Indo-European aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-persian-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "fa",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "Russian/Polish/other Slavic aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-polish-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "pl",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "Russian/Polish/other Slavic aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-russian-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "ru",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "direct Census category",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.9,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-tagalog-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "tl",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "other Indo-European aggregate",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.7,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-urdu-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "ur",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "coverage": "direct Census category",
      "census_table": "C16001",
      "estimate_year": 2023,
      "decision_status": "research_candidate"
    },
    "publisher": "U.S. Census Bureau",
    "confidence": 0.9,
    "metric_key": "acs_language_use_candidate",
    "period_end": "2023-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://data.census.gov/table/ACSDT1Y2023.C16001?q=C16001",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-language-candidate-vietnamese-acs-2023",
    "metric_value": null,
    "period_start": "2023-01-01",
    "published_on": "2024-09-12",
    "retrieved_at": "2026-07-23T01:11:58.660522+00:00",
    "source_title": "American Community Survey 2023: Language Spoken at Home",
    "claim_summary": "US Census American Community Survey language-use data includes this language or its Census language group, so it is a US research candidate—not evidence of tippos demand.",
    "language_code": "vi",
    "methodology_notes": "Census table C16001 is the source. Some entries are represented within a broader Census language group; no individual population value is inferred from an aggregate group.",
    "strategic_relevance": "Keep this language in the US research queue; validate tip-giver demand, service-worker relevance, and localization value before any product decision."
  },
  {
    "category": "tipping_regulation",
    "metadata": {},
    "publisher": "Internal Revenue Service",
    "confidence": 0.98,
    "metric_key": null,
    "period_end": "2025-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.irs.gov/taxtopics/tc761",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-large-restaurant-tip-reporting-2025",
    "metric_value": null,
    "period_start": "2025-01-01",
    "published_on": null,
    "retrieved_at": "2026-07-23T00:50:20.811281+00:00",
    "source_title": "Topic no. 761, Tips – withholding and reporting",
    "claim_summary": "United States large food and beverage establishments where tipping is customary must annually report receipts and tips to the IRS; the threshold includes normally employing more than ten people who collectively work more than 80 hours on a typical business day.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Formal reporting requirements make payroll, allocation, and auditability relevant product considerations for larger US restaurant operations."
  },
  {
    "category": "payment_adoption",
    "metadata": {},
    "publisher": "Federal Reserve Financial Services",
    "confidence": 0.95,
    "metric_key": "mobile_payments_per_consumer_month",
    "period_end": "2024-12-31",
    "source_key": "codex_public_research",
    "source_url": "https://www.frbservices.org/news/press-releases/051325-findings-from-2025-diary-of-consumer-payment-choice",
    "data_nature": "third_party",
    "metric_unit": "payments_per_month",
    "country_code": "US",
    "evidence_key": "us-mobile-payments-per-month-2024",
    "metric_value": 11,
    "period_start": "2024-01-01",
    "published_on": "2025-05-13",
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "2025 Diary of Consumer Payment Choice",
    "claim_summary": "United States consumers made an average of 11 payments per month with a mobile phone in 2024, compared with four in 2018.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Growing mobile-payment familiarity reduces user friction for a mobile-first tipping flow."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "doi": "10.1016/j.ijhm.2024.103969",
      "observations": 64
    },
    "publisher": "International Journal of Hospitality Management",
    "confidence": 0.93,
    "metric_key": "restaurant_tip_rate_trend_per_year",
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.sciencedirect.com/science/article/abs/pii/S0278431924002810",
    "data_nature": "third_party",
    "metric_unit": "percentage_points_per_year",
    "country_code": "US",
    "evidence_key": "us-restaurant-tip-trend-lynn-2025",
    "metric_value": 0.16,
    "period_start": null,
    "published_on": "2025-01-01",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "How have U.S. restaurant tips changed over time?",
    "claim_summary": "A 2025 research note found a statistically significant long-run increase in US restaurant tip percentages of about 0.16 percentage points per year.",
    "language_code": "en",
    "methodology_notes": "The paper assembled 64 observations from academic studies of real US restaurant tipping situations; OLS coefficient B=.16, SE=.03, p<.001, R-squared=.345.",
    "strategic_relevance": "Supports annual freshness in tipping guidance but does not justify inventing a universal 2026 norm for every service category."
  },
  {
    "category": "tipping_regulation",
    "metadata": {
      "applies_to": "recipient_reporting",
      "anonymity_boundary": "not_untraceable"
    },
    "publisher": "Internal Revenue Service",
    "confidence": 0.98,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.irs.gov/publications/p531",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-tip-anonymity-not-untraceable-2024",
    "metric_value": null,
    "period_start": null,
    "published_on": "2024-12-01",
    "retrieved_at": "2026-07-23T01:06:06.443693+00:00",
    "source_title": "Publication 531 (12/2024), Reporting Tip Income",
    "claim_summary": "For US employees, tips are taxable income. IRS guidance requires tip recipients to keep daily records and, when applicable, report cash, check, debit-card, and credit-card tips to their employer; electronic tip records are permitted.",
    "language_code": "en",
    "methodology_notes": "Applies to recipient income reporting; it does not itself require revealing the giver identity to a worker.",
    "strategic_relevance": "tippos may hide the giver identity from the worker or venue when appropriate, but it must not market a regulated payment as untraceable or promise anonymity from payment providers, tax reporting, fraud controls, or lawful requests."
  },
  {
    "category": "tipping_regulation",
    "metadata": {
      "applies_to": "distribution_transparency",
      "anonymity_boundary": "worker_tip_ownership"
    },
    "publisher": "U.S. Department of Labor",
    "confidence": 0.98,
    "metric_key": null,
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.dol.gov/agencies/whd/flsa/tips",
    "data_nature": "third_party",
    "metric_unit": null,
    "country_code": "US",
    "evidence_key": "us-tip-worker-ownership-privacy-context",
    "metric_value": null,
    "period_start": null,
    "published_on": null,
    "retrieved_at": "2026-07-23T01:06:06.443693+00:00",
    "source_title": "Tip Regulations under the Fair Labor Standards Act (FLSA)",
    "claim_summary": "Federal labor guidance says employers, managers, and supervisors may not keep any portion of employees’ tips; tip-pooling and recordkeeping rules may apply depending on pay arrangements.",
    "language_code": "en",
    "methodology_notes": "Federal baseline; state law may impose more protective rules.",
    "strategic_relevance": "An anonymous-tip experience should still make the destination and distribution of the money clear to the giver and protect worker tip ownership."
  },
  {
    "category": "tipping_regulation",
    "metadata": {},
    "publisher": "U.S. Department of Labor",
    "confidence": 0.98,
    "metric_key": "federal_tipped_employee_threshold",
    "period_end": null,
    "source_key": "codex_public_research",
    "source_url": "https://www.dol.gov/agencies/whd/fact-sheets/15-tipped-employees-flsa",
    "data_nature": "third_party",
    "metric_unit": "usd_tips_per_month",
    "country_code": "US",
    "evidence_key": "us-tipped-employee-threshold",
    "metric_value": 30,
    "period_start": null,
    "published_on": null,
    "retrieved_at": "2026-07-23T00:28:50.982313+00:00",
    "source_title": "Fact Sheet #15: Tipped Employees Under the FLSA",
    "claim_summary": "Federal labor guidance defines a tipped employee as someone in an occupation that customarily and regularly receives more than 30 dollars per month in tips.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "Tipping is institutionally recognized in United States labor rules, confirming a formal and recurring tipping economy."
  },
  {
    "category": "consumer_behavior",
    "metadata": {},
    "publisher": "Pew Research Center",
    "confidence": 0.95,
    "metric_key": "consumers_who_say_tipping_expected_more_places",
    "period_end": "2023-08-27",
    "source_key": "codex_public_research",
    "source_url": "https://www.pewresearch.org/wp-content/uploads/2023/11/SR_23.11.09_tipping-culture_report.pdf",
    "data_nature": "third_party",
    "metric_unit": "percent_of_us_adults",
    "country_code": "US",
    "evidence_key": "us-tipping-expectations-expanded-2023",
    "metric_value": 72,
    "period_start": "2023-08-07",
    "published_on": "2023-11-09",
    "retrieved_at": "2026-07-23T00:55:11.117869+00:00",
    "source_title": "Tipping Culture in America: Public Sees a Changed Landscape",
    "claim_summary": "Seventy-two percent of United States adults said tipping is expected in more places than it was five years earlier.",
    "language_code": "en",
    "methodology_notes": null,
    "strategic_relevance": "The product must avoid amplifying tipping fatigue; it should make a voluntary, meaningful tip feel distinct from generic checkout prompts."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "segment": "full_service_restaurants",
      "cash_tips_included": false
    },
    "publisher": "Toast",
    "confidence": 0.95,
    "metric_key": "full_service_restaurant_average_tip_rate",
    "period_end": "2026-03-31",
    "source_key": "codex_public_research",
    "source_url": "https://pos.toasttab.com/th-us/blog/data/restaurant-tipping-trends",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-toast-fsr-tip-rate-q1-2026",
    "metric_value": 19.3,
    "period_start": "2026-01-01",
    "published_on": "2026-06-24",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "Restaurant Tipping Trends",
    "claim_summary": "Toast reported a 19.3% average tip at US full-service restaurants in Q1 2026.",
    "language_code": "en",
    "methodology_notes": "Aggregated card and digital tip transactions from roughly 171,000 Toast locations as of March 31, 2026; cash tips are excluded.",
    "strategic_relevance": "Supports an 18%-20% consumer guideline while giving Tippos a measured benchmark for restaurant-related content."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "segment": "all_restaurants",
      "cash_tips_included": false
    },
    "publisher": "Toast",
    "confidence": 0.95,
    "metric_key": "restaurant_overall_average_tip_rate",
    "period_end": "2026-03-31",
    "source_key": "codex_public_research",
    "source_url": "https://pos.toasttab.com/th-us/blog/data/restaurant-tipping-trends",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-toast-overall-tip-rate-q1-2026",
    "metric_value": 18.8,
    "period_start": "2026-01-01",
    "published_on": "2026-06-24",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "Restaurant Tipping Trends",
    "claim_summary": "Toast reported an 18.8% overall average tip across US restaurant types in Q1 2026.",
    "language_code": "en",
    "methodology_notes": "Overall tips are total tips divided by gross processing volume in the Toast dataset; cash tips are excluded.",
    "strategic_relevance": "Provides a current behavioral reference point for the broad 2026 tipping-guide query."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "segment": "quick_service_restaurants",
      "cash_tips_included": false
    },
    "publisher": "Toast",
    "confidence": 0.95,
    "metric_key": "quick_service_restaurant_average_tip_rate",
    "period_end": "2026-03-31",
    "source_key": "codex_public_research",
    "source_url": "https://pos.toasttab.com/th-us/blog/data/restaurant-tipping-trends",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-toast-qsr-tip-rate-q1-2026",
    "metric_value": 15.8,
    "period_start": "2026-01-01",
    "published_on": "2026-06-24",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "Restaurant Tipping Trends",
    "claim_summary": "Toast reported a 15.8% average tip at US quick-service restaurants in Q1 2026.",
    "language_code": "en",
    "methodology_notes": "Aggregated card and digital tip transactions from Toast restaurants; the metric describes transactions that included a tip and does not measure how often consumers chose no tip.",
    "strategic_relevance": "Quantifies the gap between full-service and quick-service tipping and supports separate guidance by service model."
  },
  {
    "category": "consumer_behavior",
    "metadata": {
      "segment": "takeout",
      "cash_tips_included": false
    },
    "publisher": "Toast",
    "confidence": 0.92,
    "metric_key": "takeout_average_tip_rate",
    "period_end": "2026-03-31",
    "source_key": "codex_public_research",
    "source_url": "https://pos.toasttab.com/th-us/blog/data/restaurant-tipping-trends",
    "data_nature": "third_party",
    "metric_unit": "percent",
    "country_code": "US",
    "evidence_key": "us-toast-takeout-tip-rate-q1-2026",
    "metric_value": 13.7,
    "period_start": "2026-01-01",
    "published_on": "2026-06-24",
    "retrieved_at": "2026-07-23T02:17:23.354312+00:00",
    "source_title": "Restaurant Tipping Trends",
    "claim_summary": "Toast reported that tipped US takeout transactions averaged 13.7% in Q1 2026.",
    "language_code": "en",
    "methodology_notes": "The figure covers takeout transactions where a tip was left; it does not measure the share of takeout orders receiving no tip.",
    "strategic_relevance": "Shows why a useful product should distinguish takeout from table service instead of presenting one restaurant percentage."
  }
]
$tippos_mi_evidence$::jsonb
  ) AS x(
    evidence_key text,
    source_key text,
    country_code text,
    language_code text,
    category text,
    metric_key text,
    metric_value numeric,
    metric_unit text,
    period_start date,
    period_end date,
    claim_summary text,
    strategic_relevance text,
    publisher text,
    source_title text,
    source_url text,
    published_on date,
    retrieved_at timestamptz,
    data_nature text,
    confidence numeric,
    methodology_notes text,
    metadata jsonb
  )
)
INSERT INTO market_intelligence.market_evidence (
  evidence_key,
  source_id,
  country_code,
  language_code,
  category,
  metric_key,
  metric_value,
  metric_unit,
  period_start,
  period_end,
  claim_summary,
  strategic_relevance,
  publisher,
  source_title,
  source_url,
  published_on,
  retrieved_at,
  data_nature,
  confidence,
  methodology_notes,
  metadata
)
SELECT
  p.evidence_key,
  (SELECT s.id FROM market_intelligence.sources s WHERE s.source_key = p.source_key),
  p.country_code,
  p.language_code,
  p.category,
  p.metric_key,
  p.metric_value,
  p.metric_unit,
  p.period_start,
  p.period_end,
  p.claim_summary,
  p.strategic_relevance,
  p.publisher,
  p.source_title,
  p.source_url,
  p.published_on,
  p.retrieved_at,
  p.data_nature::market_intelligence.data_nature,
  p.confidence,
  p.methodology_notes,
  coalesce(p.metadata, '{}'::jsonb)
FROM payload p
ON CONFLICT (evidence_key) DO NOTHING;

-- Correct only the known UTF-8 double-encoding present in the captured source.
-- Exact predicates avoid overwriting independently reviewed edits.
UPDATE market_intelligence.market_evidence
SET
  publisher = 'Presidência da República',
  source_title = 'Lei 13.419 de 13 de março de 2017',
  updated_at = now()
WHERE evidence_key = 'br-tipping-law-2017'
  AND encode(convert_to(publisher, 'UTF8'), 'hex')
    = '507265736964c383c2aa6e63696120646120526570c383c2ba626c696361'
  AND encode(convert_to(source_title, 'UTF8'), 'hex')
    = '4c65692031332e343139206465203133206465206d6172c383c2a76f2064652032303137';

UPDATE market_intelligence.market_evidence
SET
  publisher = 'Banco de España',
  updated_at = now()
WHERE evidence_key IN (
  'es-bizum-p2p-preference-2024',
  'es-daily-cash-use-2024',
  'es-non-cash-operations-growth-h2-2024',
  'es-regular-card-shop-use-2024'
)
  AND encode(convert_to(publisher, 'UTF8'), 'hex')
    = '42616e636f2064652045737061c383c2b161';
